### ISSUE TITLE
How do i fix this?

### ISSUE THREAD

**Issue by nelsonfsa** [Mstpyt/EloOverlay#1]
C:\Users\Nelson\Documents\pyGUI>python eloOverlay.py
Traceback (most recent call last):
  File "C:\Users\Nelson\Documents\pyGUI\eloOverlay.py", line 6, in <module>
    from functions import api_reader
  File "C:\Users\Nelson\Documents\pyGUI\functions.py", line 1, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'

C:\Users\Nelson\Documents\pyGUI>

I''ve never used python so this might be a newbie problem!

**Comment by Mstpyt** [comment]
Hey :)
Better you use the new one :) https://github.com/Mstpyt/Faceit-Overlay

this repo here is out of the date
